apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elastic-system
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      #
      # 1) 관심 있는 네임스페이스만 남기기
      #    - solution-server
      #    - 이름이 poc- 로 시작하는 네임스페이스 (PoC용)
      #
      if !([kubernetes][namespace] == "solution-server" or [kubernetes][namespace] =~ /^poc-/) {
        drop { }
      }

      #
      # 2) 네임스페이스 기준으로 인덱스 이름을 메타데이터에 설정
      #    예: solution-server → solution-server-logs-YYYY.MM.dd
      #        poc-heartbleed → poc-heartbleed-logs-YYYY.MM.dd
      #
      mutate {
        add_field => {
          "[@metadata][target_index]" => "%{[kubernetes][namespace]}-logs-%{+YYYY.MM.dd}"
        }
      }

      # 필요하다면 이 아래에 grok/json/geoip 등 추가 필터 작성
      # ...
    }

    output {
      elasticsearch {
        hosts    => [ "${ES_HOSTS}" ]
        user     => "${ES_USER}"
        password => "${ES_PASSWORD}"

        ssl_enabled => true
        ssl_certificate_authorities => ["/etc/logstash/certificates/ca.crt"]

        # 위에서 설정한 메타데이터 기반으로 인덱스 결정
        index => "%{[@metadata][target_index]}"
      }

      stdout { codec => rubydebug }
    }
