apiVersion: v1
kind: Service
metadata:
  name: solution-server
spec:
  selector:
    app: solution-server
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
    - name: llm
      port: 9000
      targetPort: 9000
