# server/app/core/pdf_utils.py

import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
import textwrap

# 시스템에 설치된 나눔고딕 폰트 경로 (Docker 기준)
FONT_PATH = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
FONT_NAME = "NanumGothic"


def register_font():
    """한글 폰트 등록"""
    try:
        pdfmetrics.registerFont(TTFont(FONT_NAME, FONT_PATH))
        return True
    except Exception:
        return False


def draw_wrapped_text(c, text, x, y, max_width, line_height=15):
    """긴 텍스트를 줄바꿈하여 출력"""
    lines = textwrap.wrap(text, width=max_width)  # width는 글자수 대략치
    for line in lines:
        c.drawString(x, y, line)
        y -= line_height
    return y


def create_incident_pdf(incident):
    """Incident 객체를 받아 PDF 파일(BytesIO)을 생성"""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # 폰트 설정 (실패 시 기본 폰트 사용 - 한글 깨짐 주의)
    if register_font():
        font_name = FONT_NAME
    else:
        font_name = "Helvetica"

    # 1. 헤더 (타이틀)
    c.setFont(font_name, 20)
    c.drawString(50, height - 50, "Security Incident Report")

    # 구분선
    c.setLineWidth(1)
    c.line(50, height - 60, width - 50, height - 60)

    # 2. 메타데이터 (ID, 날짜, 심각도)
    c.setFont(font_name, 12)
    y = height - 100

    c.drawString(50, y, f"Incident ID: {incident.incident_id}")
    y -= 20
    c.drawString(
        50, y, f"Date: {incident.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}"
    )
    y -= 20
    c.drawString(50, y, f"Client: {incident.client_id}")
    y -= 20

    # 심각도 색상 처리
    severity = incident.status or "Unknown"
    c.setFillColor(
        colors.red if "Critical" in str(incident.incident_metadata) else colors.black
    )
    c.drawString(50, y, f"Status: {incident.status}")
    c.setFillColor(colors.black)

    y -= 40

    # 3. 요약 (Summary) - LLM 분석 결과
    c.setFont(font_name, 14)
    c.drawString(50, y, "[Analysis Summary]")
    y -= 20
    c.setFont(font_name, 10)

    summary_text = incident.summary or "No summary available."
    # 텍스트 줄바꿈 처리 (대략 80자 기준)
    y = draw_wrapped_text(c, summary_text, 50, y, 80)
    y -= 20

    # 4. 권장 조치 (Recommended Actions)
    c.setFont(font_name, 14)
    c.drawString(50, y, "[Recommended Actions]")
    y -= 20
    c.setFont(font_name, 10)

    if incident.recommended_actions:
        for action in incident.recommended_actions:
            # Action이 dict인지 str인지 확인
            act_str = (
                action.get("action", str(action))
                if isinstance(action, dict)
                else str(action)
            )
            c.drawString(60, y, f"- {act_str}")
            y -= 15
    else:
        c.drawString(60, y, "- No specific actions recommended.")
        y -= 15

    y -= 20

    # 5. 기술적 세부사항 (ATT&CK 등)
    c.setFont(font_name, 14)
    c.drawString(50, y, "[Technical Details]")
    y -= 20
    c.setFont(font_name, 10)

    meta = incident.incident_metadata or {}
    attack = incident.attack_mapping or []

    c.drawString(50, y, f"Confidence Score: {incident.confidence}%")
    y -= 15
    c.drawString(50, y, f"MITRE ATT&CK: {', '.join(attack)}")
    y -= 15

    # 하단 푸터
    c.setFont(font_name, 8)
    c.setFillColor(colors.grey)
    c.drawString(50, 30, "Generated by Trust-SOC LLM Advisor")

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer
